// app/terms/page.js
import GlobeBackground from '../../components/GlobeBackground'

export const metadata = { title: 'Terms of Service | RESQ' }

export default function TermsPage() {
  return (
    <main className="resq-shell">
      <GlobeBackground />
      <div className="resq-content" style={{ padding: '48px 24px', maxWidth: 760, margin: '0 auto' }}>
        <div className="glass-card resq-fade-in">
          <h1 className="resq-h1" style={{ fontSize: 28 }}>Terms of Service</h1>
          <p className="resq-subtle" style={{ marginTop: 4 }}>Last updated: {new Date().toLocaleDateString()}</p>

          <h2 style={{ marginTop: 28 }}>What RESQ is</h2>
          <p className="resq-subtle">
            RESQ routes emergency reports to the responders best placed to handle them, either an institution
            (a school, workplace, hospital, police service, or community organization) a user is connected to, or,
            for a general public account, the nearest institution that has opted to receive public reports of that
            type. RESQ is a routing and coordination tool; it does not replace, and is not a substitute for,
            contacting national emergency services directly when they are available and appropriate.
          </p>

          <h2 style={{ marginTop: 20 }}>Accounts and roles</h2>
          <p className="resq-subtle">
            Institutions are created only by RESQ super admins, who also decide whether an institution is private
            (reachable only by its own code) or public (able to receive reports from general public accounts by
            location and emergency type). Institution admins manage their own responders, partner units, and
            settings, and must accept RESQ's service agreement before their institution goes live.
          </p>
          <p className="resq-subtle">
            A user account can be private, connected to one or more institutions by entering each one's code and
            switching between them at any time, or public, with no institution code, routed by nearest match instead.
            Misrepresenting your role, impersonating another person, or submitting false emergency reports is
            prohibited and may result in account suspension.
          </p>

          <h2 style={{ marginTop: 20 }}>Responders: primary, secondary, and individual</h2>
          <p className="resq-subtle">
            An institution admin assigns each responder a role: a primary responder can claim and resolve
            emergencies; a secondary responder sees the full emergency feed, logs, and team chat, and can alert
            primary responders, but cannot claim a case themselves. A responder may also be linked to a specific
            partner unit (a hospital, police post, or other service, including a single individual with no fixed
            location) so their queue only shows emergencies routed to that unit. Responders are expected to act in
            good faith when claiming and resolving emergencies. Users may report a responder's conduct to their
            institution admin from the app, and may rate a responder's handling of their case after it is resolved.
          </p>

          <h2 style={{ marginTop: 20 }}>AI safety guidance</h2>
          <p className="resq-subtle">
            Right after you trigger an emergency, RESQ shows brief, automatically generated safety guidance while
            you wait for a responder. This guidance is informational only, generated by a third-party AI service
            from the emergency type alone, and is not medical, legal, or professional advice. It does not replace
            instructions from responders, medical professionals, or emergency services.
          </p>

          <h2 style={{ marginTop: 20 }}>Triggering by SMS, USSD, or call</h2>
          <p className="resq-subtle">
            If you don't have the app, you can trigger an emergency by SMS or USSD, or by calling RESQ's number,
            carried by our telecom provider. Standard messaging/call rates from your network may apply, and are
            outside RESQ's control.
          </p>

          <h2 style={{ marginTop: 20 }}>Content you submit</h2>
          <p className="resq-subtle">
            Photos, video, voice notes, and messages you attach to an emergency are shared with the responding
            institution's responders and admin for the purpose of resolving the emergency, as described in our{' '}
            <a href="/privacy">Privacy Policy</a>. An admission/work ID number or profile picture, if your
            institution requires one, is collected once and shown to the responders and reporters you interact with.
          </p>

          <h2 style={{ marginTop: 20 }}>Records and reporting</h2>
          <p className="resq-subtle">
            Institution admins can download a full report of any resolved case, or a weekly bundle of every case
            resolved in the last week, at any time, and also receive that weekly report by email automatically. It is
            the institution's responsibility to keep its own copies of these reports for follow-up and investigation,
            per the retention terms in our <a href="/privacy">Privacy Policy</a>.
          </p>

          <h2 style={{ marginTop: 20 }}>Availability</h2>
          <p className="resq-subtle">
            RESQ is provided on an "as available" basis. Network, device, or third-party service (SMS, push
            notification, email) outages can delay or prevent delivery of an alert. RESQ does not guarantee
            uninterrupted service and is not a replacement for direct emergency calls where those are available.
          </p>

          <h2 style={{ marginTop: 20 }}>Changes</h2>
          <p className="resq-subtle">These terms may be updated as RESQ's features change; continued use after an update constitutes acceptance.</p>

          <h2 style={{ marginTop: 20 }}>Contact</h2>
          <p className="resq-subtle">
            <strong style={{ color: 'var(--resq-text-primary)' }}>RESQ App 254</strong>
            <br />
            Kisumu, Kenya
            <br />
            Email: <a href="mailto:resqapp254@gmail.com">resqapp254@gmail.com</a>
            <br />
            Phone: <a href="tel:+254794698660">+254 794 698 660</a>
          </p>
        </div>
      </div>
    </main>
  )
}
